#!/usr/bin/with-contenv bash

mkdir -p /workspace/{.extensions,.ssh}

# if [ -n "${SUDO_PASSWORD}" ] || [ -n "${SUDO_PASSWORD_HASH}" ]; then
#     echo "setting up sudo access"
#     if ! grep -q 'abc' /etc/sudoers; then
#         echo "adding abc to sudoers"
#         echo "abc ALL=(ALL:ALL) ALL" >> /etc/sudoers
#     fi
#     if [ -n "${SUDO_PASSWORD_HASH}" ]; then
#         echo "setting sudo password using sudo password hash"
#         sed -i "s|^abc:\!:|abc:${SUDO_PASSWORD_HASH}:|" /etc/shadow
#     else
#         echo "setting sudo password using SUDO_PASSWORD env var"
#         echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd abc
#     fi
# fi

[[ ! -f /workspace/.bashrc ]] && \
    cp /root/.bashrc /workspace/.bashrc
[[ ! -f /workspace/.profile ]] && \
    cp /root/.profile /workspace/.profile

# fix permissions (ignore contents of /config/workspace)
# find /config -path /config/workspace -prune -o -exec chown abc:abc {} +
chown -R abc:abc /workspace
chmod 700 /workspace/.ssh
if [ -n "$(ls -A /workspace/.ssh)" ]; then
    chmod 600 /workspace/.ssh/*
fi
