stroke = off
shade = on

; Waffel
fill = #c98a4a
shape = cone
rotate = 180, 0, 0
scale = 0.62, 1.35, 0.62
move = 0, -30, 0


; drei Kugeln unten im Kreis
fill = #f2c6dc
shape = sphere
scale = 0.50
move = -25, 50, 16

fill = #f5edb0
shape = sphere
scale = 0.50
move = 25, 50, 16

fill = #b8e6b8
shape = sphere
scale = 0.50
move = 0, 50, -22


; eine Kugel oben
fill = #fff4d6
shape = sphere
scale = 0.46
move = 0, 78, 2