background = 0.95

shape = grid


; Untere Schneekugel
shape = sphere
fill = #ffffff
stroke = off
shade = on
scale = 1.35
move = 0, 0, 0

; Mittlere Schneekugel
shape = sphere
fill = #ffffff
stroke = off
shade = on
scale = 1.05
move = 0, 85, 0

; Kopf
shape = sphere
fill = #ffffff
stroke = off
shade = on
scale = 0.75
move = 0, 155, 0


; Augen
shape = sphere
fill = #111111
stroke = off
shade = on
scale = 0.07
move = -18, 170, 30

shape = sphere
fill = #111111
stroke = off
shade = on
scale = 0.07
move = 18, 170, 30


; Nase
shape = cone
fill = #ff8c1a
stroke = off
shade = on
scale = 0.16, 0.45, 0.16
rotate = 90, 0, 0
move = 0, 158, 58


; Knöpfe
shape = sphere
fill = #222222
stroke = off
shade = on
scale = 0.08
move = 0, 105, 48

shape = sphere
fill = #222222
stroke = off
shade = on
scale = 0.08
move = 0, 75, 50

shape = sphere
fill = #222222
stroke = off
shade = on
scale = 0.08
move = 0, 45, 48


; Hutkrempe
shape = cylinder
fill = #222222
stroke = off
shade = on
scale = 0.75, 0.08, 0.75
move = 0, 188, 0

; Hut
shape = cylinder
fill = #111111
stroke = off
shade = on
scale = 0.42, 0.42, 0.42
move = 0, 208, 0