source 'https://rubygems.org'

ruby '3.4.10'

gem 'sinatra', '~> 4.2.1'
gem 'sinatra-contrib', '~> 4.2.1'
gem 'faye', '~> 1.4'
gem 'mail', '~> 2.9'
gem 'mysql2', '~> 0.5.7'
# gem 'neo4j_bolt', '~> 0.3.0'
gem 'neo4j_bolt',
    git: 'https://github.com/specht/neo4j_bolt.git',
    ref: 'e800e42d509ab5f59fc940dfd819bf951f4f1a7b'
gem 'nokogiri', '~> 1.19'
gem 'puma', '~> 8.0'
gem 'rackup', '~> 2.3'
gem 'redcarpet', '~> 3.6'
gem 'rerun', '~> 0.14'
gem 'rouge', '~> 5.1'
gem 'rubocop', '~> 1.89'

group :test do
  gem 'minitest', '~> 5.27'
end
